# go_nix_simple/BUILD.bazel

# gazelle:prefix github.com/randomizedcoder/go_nix_simple
# gazelle:map_kind go_repository go_repository //:deps.bzl%go_repository
# gazelle:repository_macro deps.bzl%go_dependencies

load("@bazel_gazelle//:def.bzl", "gazelle")

# Gazelle configuration
gazelle(
    name = "gazelle",
    prefix = "github.com/randomizedcoder/go_nix_simple",  # Your Go module path
)

exports_files(["VERSION"])
