load("@gazelle//:def.bzl", "gazelle")

# Gazelle configuration
gazelle(
    name = "gazelle",
    args = [
        "-build_file_name=BUILD.bazel",
        "-mode=fix",
    ],
    command = "update",
    prefix = "github.com/randomizedcoder/go_nix_simple",
)

# Run gazelle with specific arguments for updating Go dependencies
gazelle(
    name = "gazelle-update-repos",
    args = [
        "-from_file=go.mod",
        "-to_macro=deps.bzl%go_dependencies",
        "-prune",
    ],
    command = "update-repos",
)
