# Load necessary rules
load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_oci//oci:defs.bzl", "oci_image")
#load("@rules_oci//oci:defs.bzl", "oci_image", "oci_tarball")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

# Define the Go library for the application code
go_library(
    name = "go_nix_simple_lib",
    srcs = ["go_nix_simple.go"],
    importpath = "github.com/randomizedcoder/go_nix_simple/cmd/go_nix_simple",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_clickhouse_clickhouse_go_v2//:clickhouse-go",
        "@com_github_grafana_pyroscope_go//:pyroscope-go",
        "@com_github_nats_io_nats_go//:nats_go",
        "@com_github_pkg_profile//:profile",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/promauto",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

# https://github.com/bazel-contrib/rules_oci/blob/main/docs/go.md?plain=1

# Build binary
go_binary(
    name = "go_nix_simple",
    embed = [":go_nix_simple_lib"],
    pure = "on",
    static = "on",
    visibility = ["//visibility:public"],
)

# Package binary
pkg_tar(
    name = "go_nix_simple_layer",
    srcs = [":go_nix_simple"],
)

# Scratch image
oci_image(
    name = "image_bazel_scratch",
    base = "@rules_oci//oci/bases/scratch:scratch",
    tars = [":go_nix_simple_layer"],
    entrypoint = ["/go_nix_simple"],
)

# Distroless image
oci_image(
    name = "image_bazel_distroless",
    base = "@distroless_static",
    tars = [":go_nix_simple_layer"],
    entrypoint = ["/go_nix_simple"],
)