load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "validate-image_lib",
    srcs = ["validate-image.go"],
    importpath = "github.com/randomizedcoder/go_nix_simple/cmd/validate-image",
    visibility = ["//visibility:private"],
    deps = [
        "//vendor/github.com/docker/docker/api/types/container",
        "//vendor/github.com/docker/docker/api/types/image",
        "//vendor/github.com/docker/docker/client",
        "//vendor/github.com/docker/go-connections/nat",
        "//vendor/github.com/prometheus/common/expfmt",
        "//vendor/github.com/prometheus/common/model",
    ],
)

go_binary(
    name = "validate-image",
    embed = [":validate-image_lib"],
    visibility = ["//visibility:public"],
)
